version: "3.9"

services:
  db:
    image: postgres:15
    container_name: blog_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: blog_backend
    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn blog.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend_network

  frontend:
    build:
      context: ./frontend
    container_name: blog_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - frontend_network

volumes:
  postgres_data:

networks:
  backend_network:
  frontend_network: